[build]
  command = "npm run build"
  publish = "dist"

[[headers]]
  for = "*.js"
  [headers.values]
    Content-Type = "text/javascript"

[[headers]]
  for = "*.jsx"
  [headers.values]
    Content-Type = "text/javascript"

[[headers]]
  for = "/site.webmanifest"
  [headers.values]
    Content-Type = "application/manifest+json"

[[headers]]
  for = "*.png"
  [headers.values]
    Content-Type = "image/png"

[[headers]]
  for = "*.ico"
  [headers.values]
    Content-Type = "image/x-icon"

[[headers]]
  for = "*.svg"
  [headers.values]
    Content-Type = "image/svg+xml"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200